### PR TITLE
Omeroweb django

### PR DESCRIPTION
**Pull request by will-moore**
Moving Flask app to be an OMERO.web Django app... (depends on `omero-web` install):

```
$ cd omero_search_engine_client
$ pip install -e .
$ omero config append omero.web.apps '"omero_search_engine_client"'

$ omero config set omero.web.searchengine.url https://[SERVER]/api/v1
```
Restart `omero-web`...

Go to `/{dev-server}/searchengine/` 

Screenshot 2022-05-11 at 11 02 30

### CODE REVIEW

**Comment by khaledk2** [comment]
It looks good but:

- The delete Query clause button [`X`] does not work.
- The `add OR` button does not work.
- The `Reset the Form `button removes all the query clauses and adds a new clause with all fields aligned vertically.
- `Load ` the query from the JSON from the right-hand side text area makes the query search fields aligned vertically.
- `Attribute Browser`, double click the row in the grid is changeing the search clause fields to be aligned vertically inside the query builder.

**Comment by will-moore** [comment]
Issues above should be fixed.
I have also been trying to make code reusable elsewhere, allowing other web apps to `include` the form html and styles, add the new `js` and `css` and have a functioning form.
Trying this in https://github.com/ome/omero-web/pull/368/ - e.g. see commit Trying this in https://github.com/ome/omero-web/pull/368/commits/3c35e0fa18611979682fcf54efdece585998af2c and after...

**Comment by khaledk2** [comment]
It works fine, thanks!
I think making the code reusable is a good idea.

**Comment by joshmoore** [comment]
:+1: What's the next step here then?

**Comment by will-moore** [comment]
The build is failing due to all the Docker deployment github actions, which I didn't update.
I guess we could remove these and replace with `omero-test-infra`?
There's also a lot more to do to make various functions re-usable to other web apps. Not sure of the best way yet, but we might want a `class SearchForm` which contains the various global variables listed in the `utils.js`.
But we should probably get this merged ASAP, since it will conflict with any other PR so blocks other work.
@khaledk2 Have you tried running `omero-web` locally with this installed?

**Comment by khaledk2** [comment]
Yes, I have tested it locally after configuring and running `omero-web`. 
I think it has failed when running  `prettier.yml` (https://github.com/ome/omero_search_engine_client/runs/6489451282?check_suite_focus=true).

**Comment by joshmoore** [comment]
Ok. I'm still unclear if that means let's merge or not, so going to err on the side of not doing anything :smile:

**Comment by will-moore** [comment]
OK, so prettier is fixed (green). Also removed default setting for `SEARCH_ENGINE_URL`.

**Comment by khaledk2** [comment]
Thanks, I will merge the PR unless someone has something against it.

**Pull request merged**
