### PR TITLE
Js use searchengineapi

### PR DESCRIPTION
**Pull request by will-moore**
Work in progress...
Initial commit fixes the url for autocomplete.

But the autocomplete for 'Any' Attribute in the query builder in a bit temperamental for some reason.
Sometimes it works and sometimes not! Need to investigate....

So, not tried to tackle any other endpoints yet...

cc @khaledk2

### CODE REVIEW

**Comment by khaledk2** [comment]
I have moved `submitquery` endpoint from `searchengineclient` to `searchengine`. I do not touch the JS, I have modified the 'searchengineclient' backend to use this endpoint   In addition I have changed the returnted_results  keyword to data for the results returned from requests such as:
`https://idr-testing.openmicroscopy.org/searchengineapi/api/v1/resources/image/searchvalues/?value=pdx`

**Comment by will-moore** [comment]
@khaledk2 I was trying to use the new URL at:
https://idr-testing.openmicroscopy.org/searchengineapi//api/v1/resources/image/submitquery/ added in https://github.com/ome/omero_search_engine/commit/a589a026b5a2395cba461639fc46496b6ed71447#diff-835c6f47ac54fb871c21cbef5bff216c666d57b0fae3428031d6a3632299da23R126
hoping it would return the equivalent response as:
https://idr-testing.openmicroscopy.org/searchengine/submitquery/
but this doesn't seem to be the case - Missing `columns` etc. ?

**Comment by khaledk2** [comment]
It has been modified and will return the columns and all other data as the original `submitquery` in the `searchengineclient,` but it is needed to add return_column=True to the request; it should be something like this:
`https://idr-testing.openmicroscopy.org/searchengineapi/api/v1/resources/submitquery/?return_columns=True`
Also, there is no `image` in this endpoint URL now.
It is not deployed yet at the idr-testing.

**Comment by khaledk2** [comment]
It has been deployed at the idr-testing.

**Comment by will-moore** [comment]
@khaledk2 I think this is ready for you to review.
Most of it is fine, but I didn't understand some of `display_value_search_results()`  See `FIXME` in https://github.com/ome/omero_search_engine_client/pull/12/commits/65defcc29d4607f63e7b8b5f43a54dea84616ec5

I didn't remove any python code yet, but happy to go ahead with that in this PR or a follow-up if it's not needed any more?

**Comment by khaledk2** [comment]
When loading the first page, the backend calls `/api/v1/resources/all/keys/` and sends the results to the frontend. Also, when the user unchecks the `Show all attributes` check box, it calls the following endpoint `/get_resources_keys/` from the searchengine client which in turn calls the  `/api/v1/resources/all/keys/`  searchengine endpoint.
I think in both cases JS should do that.

In the `Attribute Browser `, I think we should keep using `Attribute` instead of `Key` in the grid column header as it is more user friendly and would be consistent with the `Query Builder` tab.

This code in the `display_value_search_results()` method can be deleted as it was added when the searchengine returned a maximum of 9999 rows, but now the searchengine does not have this restriction and returns all the rows. Apologies, I should have deleted this before.

 ` else {
      // FIXME: Don't know when this is needed or if JSON results has
      // everything we need to display this??
      $("#total_number_in_buckets").text(
        "Number of buckets: " +
          results["no_buckets"] +
          " / " +
          results["total_number_of_buckets"] +
          ", Number of " +
          resource +
          "s: " +
          results["total_number"] +
          " / " +
          results["total_number_of_images"]
      );
    }`

**Comment by will-moore** [comment]
@khaledk2 I don't know if there's a backend equivalent of https://idr-testing.openmicroscopy.org/searchengine/get_resources_keys/?mode=searchterms but this seems to need `get_restircted_search_terms()` which loads the json file in the python client code?
However, I moved the loading of `data_resources` to JS code instead of from the python code, so if/when that endpoint is available in the backend, there's only a single place to update it.

The `Attribute Browser` is still showing `Attribute` column for now (as it's using the `data:[]` keys from https://idr-testing.openmicroscopy.org/searchengineapi//api/v1/resources/all/searchvalues/?value=pdx1
I've added a rename from `Key` => `Attribute` for when that changes.

Could you deploy this PR on idr-testing so I and others can test there? Thanks

**Comment by khaledk2** [comment]
I have added support to the mode  in the searchengine endpoint  for the keys:
`/api/v1/resources/all/keys/?mode=searchterms`
I have updated the new URL into the main_page.html
In addition, I have added the following to the JS to display the Attribute, make the grid double click work, and perform the search and return results.
 ```
for (i in results["data"])
         results["data"][i]["Attribute"]=results["data"][i]["Key"]
```
Also, the "Load More Results" button was not displayed even if the returned results is less than the total search results,  I have fixed that.

I have modified that locally and deployed it at the idr-testing

**Comment by will-moore** [comment]
@khaledk2 Looks good, Thanks. So you don't need me to do any more then?
Do you want to merge/close this PR?

**Comment by khaledk2** [comment]
I think this is fine, I will merge the PR later today, Thank you.

**Pull request merged**
